# Generated by Django 3.1.3 on 2020-12-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_customer_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
